version: "3.3"
services:
  app:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    ports:
      - ${DOCKER_APP_PORT}:${DOCKER_APP_PORT}
    networks:
      - microservice

networks:
  microservice:
    external:
      name: microservice
